version: "3.9"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-volume:/data/db
  backend:
    restart: always
    environment:
      - MONGODB_URL=mongodb
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "86:80"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"

volumes:
  mongo-volume: