version: "3.9"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-volume:/data/db
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "84:84"
    depends_on:
      mongodb:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80"

volumes:
  mongo-volume: